# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f579aae5ae0ebd18fd45ae99885ca4f7edf92fe2812663748e2888134b2fb29ddb6985fdfc67e665bf2d5914cc735e2c24a8bb67f1774281df90429cee20c519

test:
  secret_key_base: f5bea6172aa63263ee3415cd4767146eaf6e9f72fb70b1c64b1ad60f87e2577c23e0526c1d567f94ca214c217a1faf85e67647e09cfa988257f7e31896ce88de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
